import Anthropic from "@anthropic-ai/sdk";
import dotenv from "dotenv";
dotenv.config();

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function generateDigest(scanResults, repoCount) {
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const totalIssues = scanResults.reduce((sum, r) => sum + r.count, 0);

  const scanData = scanResults
    .map(
      (r) => `## ${r.emoji} ${r.category} (${r.count})\n${r.summary}`
    )
    .join("\n\n");

  let htmlContent;
  try {
    const message = await client.messages.create({
      model: process.env.AI_MODEL || "claude-sonnet-4-20250514",
      max_tokens: 2000,
      messages: [
        {
          role: "user",
          content: `You are a concise DevOps assistant generating a daily GitHub digest email.

Date: ${today}
Repos scanned: ${repoCount}
Total items found: ${totalIssues}

Here are the scan results:

${scanData}

Generate a prioritized daily digest with:
1. A one-line "top of mind" priority call-out (what to fix first and why)
2. A brief summary of each category with the most critical items highlighted
3. A recommended action plan for the day (2-3 bullet points max)

Format as clean HTML suitable for an email body. Use inline styles. Keep it scannable — busy developer reading on their phone. Use a clean, modern color scheme (dark text on white, colored accent badges for severity).

Do NOT include <html>, <head>, or <body> tags — just the inner content div.`,
        },
      ],
    });
    htmlContent = message.content[0].text;
  } catch (err) {
    console.error("Claude API unavailable, using fallback digest:", err.message);
    htmlContent = scanResults
      .map(
        (r) =>
          `<div style="margin-bottom:16px;">` +
          `<h3 style="margin:0 0 8px;">${r.emoji} ${r.category} (${r.count})</h3>` +
          `<div style="font-size:14px;color:#555;white-space:pre-line;">${r.summary}</div>` +
          `</div>`
      )
      .join("");
  }

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GitHub Daily Digest — ${today}</title>
</head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:640px;margin:20px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
    <div style="background:linear-gradient(135deg,#0d1117,#161b22);padding:24px 28px;color:#fff;">
      <h1 style="margin:0;font-size:20px;font-weight:600;">📊 GitHub Daily Digest</h1>
      <p style="margin:6px 0 0;font-size:13px;color:#8b949e;">${today} · ${repoCount} repos scanned · ${totalIssues} items found</p>
    </div>
    <div style="padding:24px 28px;">
      ${htmlContent}
    </div>
    <div style="padding:16px 28px;border-top:1px solid #eee;text-align:center;">
      <p style="margin:0;font-size:12px;color:#8b949e;">Generated by GitHub Digest Agent · Powered by Claude</p>
    </div>
  </div>
</body>
</html>`;
}
